# Generated by Django 4.2.6 on 2023-12-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('africanlibrary', '0003_story_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.IntegerField(),
        ),
    ]
